### PR TITLE
Bug investigation. Possible fix.

### PR DESCRIPTION
**Pull request by jackheslop96**

### CODE REVIEW

**Review by kevincoatsworth — APPROVED** [review]

**Comment by jackheslop96** [comment]
rebuild

**Comment by jackheslop96** [comment]
rebuild

**Comment by jackheslop96** [comment]
rebuild

**Comment by jackheslop96** [comment]
rebuild

**Comment by jackheslop96** [comment]
rebuild

**Comment by jackheslop96** [comment]
rebuild

**Review by kevincoatsworth — APPROVED** [review]

**Pull request merged**
